(define (problem rosplanquadtask)
(:domain quaddeliver)
(:objects
    coke1 coke2 coke3 - coke
    q1 - quad
    wp0 wp1 wp2 wp3 wp4 wp10 - waypoint
    fl1 fl2 fl3 fl4 fl5 fl6 fl7 fl8 fl9 fl10 - fuellvl
)
(:init
    (grounded q1)
    (cokeat coke2 wp2)
    (cokeat coke1 wp1)
    (connected wp0 wp1)
    (connected wp1 wp0)
    (connected wp2 wp3)
    (connected wp4 wp1)
    (connected wp3 wp4)
    (connected wp1 wp10)
    (connected wp10 wp1)
    (keyat wp10 wp1 wp2)
    (quadat q1 wp1)
    (squaredone q1)
    (fuelmapping fl1 fl2)
    (fuelmapping fl2 fl3)
    (fuelmapping fl3 fl4)
    (fuelmapping fl4 fl5)
    (fuelmapping fl5 fl6)
    (fuelmapping fl6 fl7)
    (fuelmapping fl7 fl8)
    (fuelmapping fl8 fl9)
    (fuelmapping fl9 fl10)
    (quadfuel fl10)
    (maximumfuel fl10)
    (minimumfuel fl1)
    (stationat wp2)
)
(:goal (and
    (cokeat coke1 wp2)
    (cokeat coke2 wp3))
))
